# Basic example of docker compose
version: "2"
services:
  mongo:
    container_name: mongo
    image: mongo
    ports:
      - "27017:27017"
  front:
    container_name: angular
    restart: always
    build: FE/
    ports:
      - "8080:80"
  back:
    container_name: nodejs
    restart: always
    build: BE/
    ports:
      - "4000:4000"
    links:
      - mongo